### ISSUE TITLE
Cannot include shuffle plugin

### ISSUE THREAD

**Issue by Ruperr** [cashshuffle/cashshuffle-electron-cash-plugin#21]
```
File "/home/xxx/xxx/Electron Cash-3.1.2/lib/plugins.py", line 199, in run_hook
    r = f(*args)
  File "/home/xxxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 77, in init_qt
    self.on_new_window(window)
  File "/home/xxxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 81, in on_new_window
    self.update(window)
  File "/home/xxxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 96, in update
    self.set_coinshuffle_addrs()
  File "/home/xxxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 118, in set_coinshuffle_addrs
    self.coinshuffle_inputs.setItmes(self.window.wallet)
  File "/home/xxxx/xxx/plugins/shuffle/shuffle.py", line 99, in setItmes
    self.addItem(utxo.get('address')+': '+ self.amounted_value(utxo['value']))
TypeError: can only concatenate tuple (not "str") to tuple
```

This is showing up in the terminal when I tick the cashshuffle box

**Comment by clifordsymack** [comment]
@Ruperr i updated for changes in electroncash. Should work now

**Comment by Ruperr** [comment]
Plugin is now included, but wallet is crashing when I click on shuffle

```
Traceback (most recent call last):
  File "/home/xxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 258, in <lambda>
    self.coinshuffle_start_button = EnterButton(_("Shuffle"),lambda :self.start_coinshuffle_protocol())
  File "/home/xxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 213, in start_coinshuffle_protocol
    sk = regenerate_key(deserialize_privkey(priv_key[0])[1])
  File "/home/xxx/xxx/Electron Cash-3.1.2/lib/bitcoin.py", line 437, in deserialize_privkey
    raise BaseException("cannot deserialize", key)
BaseException: ('cannot deserialize', 'L')
```

**Comment by clifordsymack** [comment]
@Ruperr will discover it.

**Comment by clifordsymack** [comment]
@Ruperr I've updated the code. Can you check it?

**Comment by Ruperr** [comment]
The servers cashshuffle and coinmix are working. But looks like there aren't enough players to begin, since there's no progress. But otherwise it seems to be okay, no errors in the terminal.

I believe that the onion server isn't working since the wallet is crashing. But I didn't configure the wallet to run by proxy, so maybe this might be the problem? Otherwise I was just testing all three servers.

For your information error log when I choose the onion server:

```
Traceback (most recent call last):
  File "/xxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 259, in <lambda>
    self.coinshuffle_start_button = EnterButton(_("Shuffle"),lambda :self.start_coinshuffle_protocol())
    File "/xxx/xxx/Electron Cash-3.1.2/plugins/shuffle/qt.py", line 215, in start_coinshuffle_protocol
    self.pThread = protocolThread(server, port, self.window.network, amount, fee, sk, pub_key, output_address, change_address, logger = logger, ssl = ssl)
    File "/xxx/xxx/Electron Cash-3.1.2/plugins/shuffle/client.py", line 49, in __init__
    self.commutator.connect(host, port)
  File "/xxx/xxx/Electron Cash-3.1.2/plugins/shuffle/commutator_thread.py", line 67, in connect
    self.logger.put(str(e))
AttributeError: 'NoneType' object has no attribute 'put'
```

**Comment by ifol** [comment]
> But looks like there aren't enough players to begin, since there's no progress.

I have the same issue, could not complete a single shuffle, is this plugin actually working for somebody at all?

@clifordsymack could you please address these issues? I'd love to have this plugin working.

**Comment by clifordsymack** [comment]
Hi @ifol ! Yes you need someone to do the shuffling with :) . I supposed we need to make some kind of schedule thing or something like that to make players meeting for shuffling more often. Will mediate about it

**Comment by ifol** [comment]
Adoption should take care of that, but the plugin needs to work first without the hiccups. There are plenty of issues that need to be solved so focus on that and then maybe organize a shuffle party in reddit ;) provide a donation address, so people can chip in if it works well to fund further developement.

**Comment by clifordsymack** [comment]
I recommend to use installation via zip file. It is available in electron-cash now.
