### ISSUE TITLE
ValueError: Same public keys appears!

### ISSUE THREAD

**Issue by ifol** [cashshuffle/cashshuffle-electron-cash-plugin#22]
Hi, I've got this error after clicking on Shuffle button:

```
<ssl.SSLSocket fd=26, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "[...]/Electron Cash-3.1.2/plugins/shuffle/client.py", line 118, in run
    self.change)
  File "[...]/Electron Cash-3.1.2/plugins/shuffle/coin_shuffle.py", line 55, in __init__
    raise ValueError('Same public keys appears!')
ValueError: Same public keys appears!
```

In Electron Cash console I see:

```
Console output go here
Player 3 get session number.

Player 3 is about to share verification key with 3 players.

Player 3 get 3.
```

Nothing after that so far.

**Comment by clifordsymack** [comment]
@ifol Looks like you play with yourself in shuffle round. This should not appear basically. Will check it

**Comment by ifol** [comment]
May be, because I shut down Electron a tried another shuffle, probably the session did not timeout on the server yet. That's why a CANCEL button is needed.

**Comment by clifordsymack** [comment]
We add cancel button. Should not behave that way now.
