### ISSUE TITLE
type_checkers.py Type Error

### ISSUE THREAD

**Issue by bitcoineler** [cashshuffle/cashshuffle-electron-cash-plugin#27]
I used electroncash 3.1.2 and got this error when shuffling:

protocol started
cRYZprfgFVr6BAXSngngkACBye5QuVwbbdXAVdCfLCZu9vQBdimi
<socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.2-py3.5.egg/electroncash_plugins/shuffle/coin_shuffle.py", line 208, in protocol_definition
    self.broadcast_new_key()
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.2-py3.5.egg/electroncash_plugins/shuffle/coin_shuffle.py", line 128, in broadcast_new_key
    self.__messages.add_encryption_key(self.__crypto.export_public_key(), self.__change)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.2-py3.5.egg/electroncash_plugins/shuffle/messages.py", line 105, in add_encryption_key
    if change : packet.packet.message.address.address = change
  File "/usr/local/lib/python3.5/dist-packages/protobuf-3.5.1-py3.5.egg/google/protobuf/internal/python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/usr/local/lib/python3.5/dist-packages/protobuf-3.5.1-py3.5.egg/google/protobuf/internal/type_checkers.py", line 177, in CheckValue
    raise TypeError(message)
TypeError: <Address qzruqvjj5u0wdhmt4n9yg3y0n40q8yky8vaq28mzmm> has type <class 'electroncash.address.Address'>, but expected one of: (<class 'bytes'>, <class 'str'>)

**Comment by clifordsymack** [comment]
Should work now.
