### ISSUE TITLE
Non-hexadecimal number found in from_hex()...

### ISSUE THREAD

**Issue by checksum0** [cashshuffle/cashshuffle-electron-cash-plugin#9]
Please see traceback below, result of a failed shuffling round between three shufflers.

Exception in thread Thread-29:
Traceback (most recent call last):
  File "C:\Users\iande\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\iande\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\fresh\Electron Cash-3.0\plugins\shuffle\coin_shuffle.py", line 315, in protocol_definition
    signature = self.__coin.get_transaction_signature(self.transaction, self.__sk, self.__vk)
  File "D:\fresh\Electron Cash-3.0\plugins\shuffle\coin.py", line 65, in get_transaction_signature
    pre_hash = Hash(bfh(tx.serialize_preimage(tx_num)))
  File "D:\fresh\Electron Cash-3.0\lib\transaction.py", line 711, in serialize_preimage
    hashOutputs = bh2u(Hash(bfh(''.join(self.serialize_output(o) for o in outputs))))
  File "D:\fresh\Electron Cash-3.0\lib\transaction.py", line 711, in <genexpr>
    hashOutputs = bh2u(Hash(bfh(''.join(self.serialize_output(o) for o in outputs))))
  File "D:\fresh\Electron Cash-3.0\lib\transaction.py", line 690, in serialize_output
    s = int_to_hex(amount, 8)
  File "D:\fresh\Electron Cash-3.0\lib\bitcoin.py", line 206, in int_to_hex
    return rev_hex(s)
  File "D:\fresh\Electron Cash-3.0\lib\bitcoin.py", line 199, in rev_hex
    return bh2u(bfh(s)[::-1])
ValueError: non-hexadecimal number found in fromhex() arg at position 12

**Comment by zquestz** [comment]
This was fixed.
